package: anypytools
user: melund

platform:
  - linux-64
engine:
  - python=2.7
  - python=3.4


script:
  - conda build conda.recipe

after_success:
  - conda convert -p win-32 /opt/miniconda/conda-bld/linux-64/anypytools-*.tar.bz2 -o /opt/miniconda/conda-bld
  - conda convert -p win-64 /opt/miniconda/conda-bld/linux-64/anypytools-*.tar.bz2 -o /opt/miniconda/conda-bld

  
  
build_targets:
   - /opt/miniconda/conda-bld/win-32/*.tar.bz2
   - /opt/miniconda/conda-bld/win-64/*.tar.bz2

notifications:
  email:
    recipients: ['melund@gmail.com']

