package:
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.0') }}
  name: anypytools     # lower case name of package, may contain '-' but no spaces

source:
   git_url: ../

build:          
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  # Added to allow the pytest entry points in setup.py to work
  # This is also the reason for setuptools beeing a runtime dependency. 
  preserve_egg_dir: True
  
  
# the build and runtime requirements:
requirements:     # (optional)
  build:
    - setuptools
    - python
    - future
    
  run:
    - python
    - pywin32 # [win and py27]
    - future >=0.15
    - h5py >=2.5
    - setuptools
    - scipy >=0.15
    - jupyter >=1.0
    - ipywidgets >=5.1
    - ipython >=5.0
    
test:
  requires:
    - pytest

#  commands:
#    - python -c "import anypytools; anypytools.test()"

app:
    entry: ipython notebook ${PREFIX}/AnyPyToolsTutorial/00_AnyPyTools_tutorial.ipynb
    summary: AnyPyTools Tutorial
    icon: apt_icon.png
#    type: web
#    cli_opts:
#        args: --notebook-dir %s
#        default: "${PREFIX}/AnyPyToolsTutorial 00_AnyPyTools_tutorial.ipynb"
#        name: "Start directory"

    


about:            # (optional)
  home: https://github.com/AnyBody-Research-Group/AnyPyTools
  license: MIT