package:
  name: anypytools     # lower case name of package, may contain '-' but no spaces
  version: {{ environ['GIT_DESCRIBE_TAG'] }}
source:
  git_url: https://github.com/AnyBody-Research-Group/AnyPyTools.git

build:            # (optional)
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  # Added to allow the pytest entry points in setup.py to work
  # This is also the reason for setuptools beeing a runtime dependency. 
  preserve_egg_dir: True
  
  
# the build and runtime requirements:
requirements:     # (optional)
  build:
    - setuptools
    - python
    - future
    
  run:
    - python
    - pywin32 # [win]
    - future
    - h5py
    - setuptools
    - scipy
    - ipython-notebook >=3.0
    - ipython-qtconsole >=3.0
    
test:
  requires:
    - pytest

#  commands:
#    - python -c "import anypytools; anypytools.test()"

app:
    entry: ${PREFIX}\Scripts\AnyPyToolsTutorial.bat
    summary: AnyPyTools Tutorial
    icon: apt_icon.png
#    type: web
#    cli_opts:
#        args: --notebook-dir %s
#        default: "${PREFIX}/AnyPyToolsTutorial 00_AnyPyTools_tutorial.ipynb"
#        name: "Start directory"

    


about:            # (optional)
  home: https://github.com/AnyBody-Research-Group/AnyPyTools
  license: MIT