package:
  name: anypytools     
  version: {{ GIT_DESCRIBE_TAG + '.dev' + GIT_DESCRIBE_NUMBER }}

source:
   git_url: ../

build:          
  number: 0
  #string: {{'py' + CONDA_PY + '_' + GIT_DESCRIBE_HASH }}
  # Added to allow the pytest entry points in setup.py to work
  # This is also the reason for setuptools beeing a runtime dependency. 
  preserve_egg_dir: True
  
  
# the build and runtime requirements:
requirements:     # (optional)
  build:
    - setuptools
    - python
    - future
    
  run:
    - python
    - pywin32 # [py27 or py34]
    - future >=0.15
    - h5py >=2.5
    - setuptools
    - scipy >=0.15
    - ipywidgets >=5.1
    - notebook >=4.2
    - jupyter >=1.0
    
test:
  imports:
    - anypytools
    - anypytools.abcutils
    - anypytools.macro_commands
#  commands:
#    - python -c "import anypytools; anypytools.test()"

app:
    entry: jupyter notebook %PREFIX%\\share\\notebooks\\anypytools\\00_AnyPyTools_tutorial.ipynb
    summary: AnyPyTools Tutorial
    icon: apt_icon.png
#    type: web
#    cli_opts:
#        args: --notebook-dir %s
#        default: "${PREFIX}/AnyPyToolsTutorial 00_AnyPyTools_tutorial.ipynb"
#        name: "Start directory"


about:
  home: https://github.com/AnyBody-Research-Group/AnyPyTools
  license: MIT
  summary: Python tools and utilities for working with the AnyBody Modelling System
